export enum Generic {
  GetStores = 'GET_STORES',
  GetStoresByAlphabet = 'GET_STORES_BY_ALPHABET',
  GetStore = 'GET_STORE',
  GetProducts = 'GET_PRODUCTS',
  GetStoresBySearchText = 'GET_STORES_BY_SEARCH_TEXT',
  GetProductsBySearchText = 'GET_PRODUCTS_BY_SEARCH_TEXT',
  GetReferrals = 'GET_REFERRALS',
  GetRewards = 'GET_REWARDS',
  GetSettings = 'GET_SETTINGS',
  GetWallets = 'GET_WALLETS',
  GetAuthToken = 'GET_AUTH_TOKEN',
  GetSessionId = 'GET_SESSION_ID',
  GetCurrentTabId = 'GET_CURRENT_TAB_ID',
  AuthTabId = 'AUTH_TAB_ID',
  PostLogin = 'POST_LOGIN',
  PostSegment = 'POST_SEGMENT',
  OpenAffiliateInTab = 'OPEN_AFFILIATE_IN_TAB',
  ToolBarIconAndBadgeValue = 'TOOLBAR_ICON_AND_BADGE_VALUE',
  CheckStore = 'CHECK_STORE',
  UserInfo = 'USER_INFO',
}
